# Generated by Django 4.1.1 on 2022-09-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id_coach', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('role', models.CharField(choices=[(1, 'Técnico'), (2, 'Asistente'), (3, 'Médico'), (4, 'Preparador')], default='Técnico', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id_position', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=5, verbose_name='Abreviación')),
                ('position_description', models.CharField(max_length=20, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Posicion',
                'verbose_name_plural': 'Posiciones',
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id_team', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(help_text='Ej: Mexico', max_length=20, verbose_name='Nombre')),
                ('team_flag', models.ImageField(upload_to='media', verbose_name='Bandera nacional')),
                ('team_shield', models.ImageField(upload_to='media', verbose_name='Escudo')),
            ],
            options={
                'verbose_name': 'Equipos',
                'verbose_name_plural': 'Equipos',
                'db_table': 'teams',
            },
        ),
    ]
