# Generated by Django 4.1.1 on 2022-09-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'Tecnico', 'verbose_name_plural': 'Tecnicos'},
        ),
        migrations.AlterModelTable(
            name='coach',
            table='coach',
        ),
    ]
