# Generated by Django 4.1.1 on 2022-09-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_app', '0002_alter_coach_options_alter_coach_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_description',
            field=models.CharField(help_text='Ej: Portero', max_length=20, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_name',
            field=models.CharField(help_text='Ej: PO', max_length=5, verbose_name='Abreviación'),
        ),
    ]
