# Generated by Django 4.1.1 on 2022-09-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_app', '0003_alter_position_position_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_description',
            field=models.CharField(help_text='Ej: Portero', max_length=50, verbose_name='Descripción'),
        ),
    ]
