# Generated by Django 4.1.1 on 2022-09-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_app', '0005_coach_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id_player', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('photo', models.ImageField(upload_to='media', verbose_name='Foto')),
                ('shirt_number', models.CharField(max_length=50)),
                ('initial_player', models.CharField(choices=[(1, 'Si'), (2, 'No')], max_length=20, verbose_name='Titular')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa_app.position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa_app.team')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'players',
            },
        ),
    ]
