# Generated by Django 4.1.1 on 2022-09-15 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_app', '0006_alter_coach_nationality_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa_app.position', verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shirt_number',
            field=models.IntegerField(max_length=50, verbose_name='Número de camiseta'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa_app.team', verbose_name='Seleccion nacional'),
        ),
    ]
