# Generated by Django 4.1.1 on 2022-09-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_app', '0007_alter_player_position_alter_player_shirt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='initial_player',
            field=models.CharField(choices=[('1', 'Si'), ('2', 'No')], max_length=20, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shirt_number',
            field=models.IntegerField(verbose_name='Número de camiseta'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id_position',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
