# Generated by Django 4.1.1 on 2022-09-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_app', '0008_alter_player_initial_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='role',
            field=models.CharField(choices=[('1', 'Técnico'), ('2', 'Asistente'), ('3', 'Médico'), ('4', 'Preparador')], default='Técnico', max_length=15),
        ),
    ]
